# Generated by Django 4.0.4 on 2022-04-19 14:39

from django.db import migrations, models
import django.utils.timezone
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_player2_alter_game_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[games.models.check_date], verbose_name='開始日時'),
        ),
    ]
